weather:
  monitored_fields:
    - temperature_2m
    - relative_humidity_2m
    - precipitation
    - wind_speed_10m
    - dew_point_2m

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  stream: "weather_metrics"
